[profile.default]
optimizer = true
optimizer_runs = 500
libs = ["lib"]   # let forge see lib/ and node_modules/
solc_version = "0.8.25"          # match OZ v5 / mcopy

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]
